name: Django CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up environment variables
        run: |
          echo "DEBUG=False" >> .env
          echo "ENVIRONMENT=testing" >> .env

      - name: Run tests
        run: |
          python manage.py test

  build-and-push:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/django-app:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/django-app:${{ github.sha }}

      - name: Tag as latest
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/django-app:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/django-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/django-app:latest
